import Logics.Homomorphism

/-!
# Filters and their quotients

A filter is a set of elements closed upwards and under meets, a set of things
"true enough".  Declaring everything in a filter to be the top collapses the
algebra onto a quotient, and that quotient is again a Heyting algebra.

The construction is the algebraic half of adding axioms to a logic: the filter
generated by a formula's instances is what the Lindenbaum algebra of a schema
quotients by.  Its use here is more basic.  A homomorphic image cannot be
exhibited at all without a way to build one, and filters build them: every
filter yields a quotient together with a surjection onto it, so
`FilterQuot.onto` supplies the ingredient that the order on algebras is defined
in terms of.

Two elements are identified when each implies the other by an amount lying in
the filter.  That the connectives respect this is exactly what the implication
identities of `Logics/Heyting.lean` say.
-/

open PartialOrder Lattice BoundedLattice HeytingAlgebra

/-! ## Filters -/

/-- A set of elements containing the top, closed upwards and under meets. -/
structure Filter (α : Type u) [HeytingAlgebra α] where
  mem : α → Prop
  top_mem : mem ⊤
  upward : ∀ {a b : α}, mem a → a ⊑ b → mem b
  inf_mem : ∀ {a b : α}, mem a → mem b → mem (a ⊓ b)

namespace Filter

variable {α : Type u} [HeytingAlgebra α] (F : Filter α)

/-- An implication between comparable elements is in every filter. -/
theorem mem_of_le {x y : α} (h : x ⊑ y) : F.mem (x ⇨ y) :=
  F.upward F.top_mem (le_of_eq (himp_eq_top_of_le h).symm)

/-- Implications in a filter compose. -/
theorem mem_himp_trans {x y z : α} (h₁ : F.mem (x ⇨ y)) (h₂ : F.mem (y ⇨ z)) :
    F.mem (x ⇨ z) :=
  F.upward (F.inf_mem h₁ h₂) (himp_trans x y z)

/-- Two elements are identified when each implies the other by an amount in the
filter. -/
def cong (a b : α) : Prop := F.mem (a ⇨ b) ∧ F.mem (b ⇨ a)

/-- The induced setoid.  It is not an instance, since there is one for every
filter. -/
def setoid : Setoid α where
  r := F.cong
  iseqv :=
    ⟨fun _ => ⟨F.mem_of_le le_rfl, F.mem_of_le le_rfl⟩,
     fun h => ⟨h.2, h.1⟩,
     fun h₁ h₂ => ⟨F.mem_himp_trans h₁.1 h₂.1, F.mem_himp_trans h₂.2 h₁.2⟩⟩

/-- The principal filter above an element: the supply of concrete quotients. -/
def up (x : α) : Filter α where
  mem b := x ⊑ b
  top_mem := le_top x
  upward h hb := le_trans h hb
  inf_mem h₁ h₂ := le_inf h₁ h₂

@[simp] theorem up_mem {x y : α} : (up x).mem y ↔ x ⊑ y := Iff.rfl

end Filter

/-- The algebra of an algebra modulo a filter. -/
def FilterQuot {α : Type u} [HeytingAlgebra α] (F : Filter α) : Type u :=
  Quotient F.setoid

namespace FilterQuot

variable {α : Type u} [HeytingAlgebra α] {F : Filter α}

/-- The class of an element. -/
def mk (F : Filter α) (a : α) : FilterQuot F := Quotient.mk F.setoid a

theorem mk_eq_mk {a b : α} : mk F a = mk F b ↔ F.cong a b := by
  constructor
  · exact fun h => Quotient.exact h
  · exact fun h => Quotient.sound h

/-! ## The operations

Each one descends because a pair of implications in the filter bounds the
implication between the combined elements. -/

def le (x y : FilterQuot F) : Prop :=
  Quotient.liftOn₂ x y (fun a b => F.mem (a ⇨ b))
    (fun _ _ _ _ ha hb => propext
      ⟨fun h => F.mem_himp_trans (F.mem_himp_trans ha.2 h) hb.1,
       fun h => F.mem_himp_trans (F.mem_himp_trans ha.1 h) hb.2⟩)

def inf (x y : FilterQuot F) : FilterQuot F :=
  Quotient.liftOn₂ x y (fun a b => mk F (a ⊓ b))
    (fun a b a' b' ha hb => Quotient.sound
      ⟨F.upward (F.inf_mem ha.1 hb.1) (himp_inf_congr a b a' b'),
       F.upward (F.inf_mem ha.2 hb.2) (himp_inf_congr a' b' a b)⟩)

def sup (x y : FilterQuot F) : FilterQuot F :=
  Quotient.liftOn₂ x y (fun a b => mk F (a ⊔ b))
    (fun a b a' b' ha hb => Quotient.sound
      ⟨F.upward (F.inf_mem ha.1 hb.1) (himp_sup_congr a b a' b'),
       F.upward (F.inf_mem ha.2 hb.2) (himp_sup_congr a' b' a b)⟩)

def himp (x y : FilterQuot F) : FilterQuot F :=
  Quotient.liftOn₂ x y (fun a b => mk F (a ⇨ b))
    (fun a b a' b' ha hb => Quotient.sound
      ⟨F.upward (F.inf_mem ha.2 hb.1) (himp_himp_congr a b a' b'),
       F.upward (F.inf_mem ha.1 hb.2) (himp_himp_congr a' b' a b)⟩)

@[simp] theorem le_mk (a b : α) : le (mk F a) (mk F b) ↔ F.mem (a ⇨ b) := Iff.rfl
@[simp] theorem inf_mk (a b : α) : inf (mk F a) (mk F b) = mk F (a ⊓ b) := rfl
@[simp] theorem sup_mk (a b : α) : sup (mk F a) (mk F b) = mk F (a ⊔ b) := rfl
@[simp] theorem himp_mk (a b : α) : himp (mk F a) (mk F b) = mk F (a ⇨ b) := rfl

/-! ## The Heyting algebra -/

instance : PartialOrder (FilterQuot F) where
  le := le
  le_refl x := Quotient.inductionOn x (fun _ => F.mem_of_le le_rfl)
  le_trans {x y z} := by
    refine Quotient.inductionOn₃ x y z (fun _ _ _ h₁ h₂ => ?_)
    exact F.mem_himp_trans h₁ h₂
  le_antisymm {x y} := by
    refine Quotient.inductionOn₂ x y (fun _ _ h₁ h₂ => ?_)
    exact mk_eq_mk.mpr ⟨h₁, h₂⟩

instance : Lattice (FilterQuot F) where
  inf := inf
  sup := sup
  inf_le_left x y := Quotient.inductionOn₂ x y (fun a b => F.mem_of_le (inf_le_left a b))
  inf_le_right x y := Quotient.inductionOn₂ x y (fun a b => F.mem_of_le (inf_le_right a b))
  le_inf {x y z} := by
    refine Quotient.inductionOn₃ x y z (fun a b c h₁ h₂ => ?_)
    exact F.upward (F.inf_mem h₁ h₂) (himp_le_inf a b c)
  le_sup_left x y := Quotient.inductionOn₂ x y (fun a b => F.mem_of_le (le_sup_left a b))
  le_sup_right x y := Quotient.inductionOn₂ x y (fun a b => F.mem_of_le (le_sup_right a b))
  sup_le {x y z} := by
    refine Quotient.inductionOn₃ x y z (fun a b c h₁ h₂ => ?_)
    exact F.upward (F.inf_mem h₁ h₂) (sup_himp_le a b c)

instance : BoundedLattice (FilterQuot F) where
  top := mk F ⊤
  bot := mk F ⊥
  le_top x := Quotient.inductionOn x (fun a => F.mem_of_le (le_top a))
  bot_le x := Quotient.inductionOn x (fun a => F.mem_of_le (bot_le a))

instance : HeytingAlgebra (FilterQuot F) where
  himp := himp
  himp_adj x y z := by
    refine Quotient.inductionOn₃ x y z (fun a b c => ?_)
    show F.mem ((a ⊓ b) ⇨ c) ↔ F.mem (a ⇨ (b ⇨ c))
    rw [himp_curry]

/-! ## The quotient is a homomorphic image

This is the point of the file: it exhibits a surjection, so `Onto` can be
established rather than merely assumed. -/

/-- The quotient map. -/
def mkHom (F : Filter α) : Hom α (FilterQuot F) where
  toFun := mk F
  map_bot := rfl
  map_top := rfl
  map_inf _ _ := rfl
  map_sup _ _ := rfl
  map_himp _ _ := rfl

theorem mkHom_surjective (F : Filter α) : Function.Surjective (mkHom F).toFun :=
  fun x => Quotient.exists_rep x

/-- **Every filter quotient is a homomorphic image.** -/
theorem onto (F : Filter α) : Onto (FilterQuot F) α :=
  ⟨mkHom F, mkHom_surjective F⟩

/-- An element reaches the top of the quotient exactly when it is in the
filter. -/
theorem mk_eq_top_iff (F : Filter α) (a : α) : mk F a = ⊤ ↔ F.mem a := by
  constructor
  · intro h
    have h' := (mk_eq_mk.mp h).2
    rwa [himp_top_left] at h'
  · intro h
    refine mk_eq_mk.mpr ⟨F.mem_of_le (le_top a), ?_⟩
    rwa [himp_top_left]

/-- Validity passes to every quotient. -/
theorem valid_of_valid (F : Filter α) {p : Form}
    (h : ∀ v : Nat → α, p.eval v = ⊤) : ∀ w : Nat → FilterQuot F, p.eval w = ⊤ :=
  valid_of_onto (onto F) h

/-- **A filter quotient sits below its algebra in the order on algebras.**  This
is the first way to establish `SH` other than by reflexivity. -/
theorem sh_of_filter {α : Type} [HeytingAlgebra α] (F : Filter α) :
    SH (FilterQuot F) α :=
  ⟨FilterQuot F, inferInstance, onto F, embeds_refl _⟩

end FilterQuot
